services:
  db:
    build:
      context: .
      dockerfile: Dockerfile        # ← este es el de MySQL en la raíz
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ferremas_db
      MYSQL_USER: carlos
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root_secret_password
    volumes:
      - ferremas_db_data:/var/lib/mysql
    networks: [ferremas-net]

  backend:
    build:
      context: ./ferremas_backend    # carpeta con el pom.xml y su Dockerfile
      dockerfile: Dockerfile
    depends_on: [db]                 # arranca después de MySQL
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ferremas_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: carlos
      SPRING_DATASOURCE_PASSWORD: 1234
      JWT_SECRET: 45EwlUqLa6quE55RGwY/vd9IUjLideoUwA4XdM7dEaU=
      JWT_EXPIRATION: 86400000
    networks: [ferremas-net]

volumes:
  ferremas_db_data:

networks:
  ferremas-net:
